import { inter } from '@/app/ui/fonts';
import "@/app/ui/globals.css";

export const metadata = {
  title: "Swift Pay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
